### PR TITLE
Add video example

### PR DESCRIPTION
**Pull request by gbryant-arm**
This PR aims at adding a video example to this repository.
The final goal is to read an H264 video from the virtual filesystem, decode it inside Veracruz and output individual frames, which will be used in an independent example as input for a tensorflow model.
This implies porting a video codec, openh264, to WebAssembly.

Status:
* Changed openh264 build to compile it to WASM
* Dirty trick to disable multithreading
* Successfully compiled a basic C++ video decoding example using openh264 and openh264-dec, with the emscripten toolchain. Issue: emscripten's glue code is hard to get rid of
* Successfully compiled the same example with wasi sdk's toolchain
* Debugged example execution inside Veracruz
  * Bugs:
    * VC's wasi: bad specification of `clock_time_get` (FIXED)
    * wasi types: bad implementation of fseek's position indicators (mismatch with libc) (FIXED)
    * wasm32 program fails when file descriptor returned by `path_open` is bigger than 2**31 (FIXED)
    * when a directory other than the root directory is installed in the VFS, the wasm program tries to read files from it, even though no file is attached to that directory (FIXED)

TODO:
* ~~Write Rust example using bindgen to expose `openh264-dec`~~
* ~~Add  licensing &authorship to Makefiles and source files~~

### CODE REVIEW

**Comment by dominic-mulligan-arm** [comment]
What is causing the linking issue, @gbryant-arm?

**Comment by gbryant-arm** [comment]
[`openh264-sys`](https://github.com/kkk669/rust-openh264-sys) doesn't support WASM.
The code downloading and compiling openh264 and calling bindgen to generate the bindings doesn't produce a WASM static library, which is required to produce a WASM binary.
I guess I have to change `build.rs` in `openh264-sys` to compile openh264 to WASM before linking.
I get the same error with [`tensorflow`](https://github.com/tensorflow/rust), the same solution might apply there too.

**Review by mofanv — DISMISSED** [review]

**Comment by gbryant-arm** [comment]
Ready for review

**Comment by dreemkiller** [comment]
Is this still relevant?

**Comment by gbryant-arm** [comment]
It's a subset of VOD now. I suggest we close it

**Pull request closed without merging**
